### ISSUE TITLE
use more strict file path matching

### ISSUE THREAD

**Issue by kaeff** [taptapship/wiredep#108]
Give a source file that contains a commented-out script tag referencing an external file, say accidentally or during development, like so:

    

When a bower component that exports a "somescript.js" file, the component's file won't be injected.

I suspect that in `inject-dependencies.js`, since `somescript.js` becomes an entry in `filesCaught`, the component's file will be rejected from the found dependencies.

**Comment by eddiemonge** [comment]
I dont think this is valid in 3.0.0. If I'm wrong and someone can give me an example (preferably as a test case) I'll reopen and add code for it
