### ISSUE TITLE
CLI: read from configuration file

### ISSUE THREAD

**Issue by stephenplusplus** [taptapship/wiredep#110]
We should allow a user to specify a config file from the cli, such as:

```sh
$ wiredep -c wiredep_config.json
```

**Comment by Parakleta** [comment]
If possible I think I would like this to default to reading from a parameter in the bower.json file.  I have roughly implemented this by modifying wiredep-cli.js to ensure `bowerJson` is parsed and then passing `extend({}, bowerJson.wiredep, argv)` into the `wiredep()` call.

**Comment by eddiemonge** [comment]
Still seems valid. PR still welcome

**Comment by Parakleta** [comment]
I posted my modified version as a gist.  I don't use wiredep anymore but you're welcome to take from it what you need.

https://gist.github.com/Parakleta/cf74e7e435f38cb6cb37

The main work is done by line 72 which merges the arguments with the `wiredep` entry in the `bower.json` file, the rest is just refactoring.

**Comment by eddiemonge** [comment]
Added this here: https://github.com/taptapship/wiredep/tree/configFile but not sure how to really test it. Need to mock out wiredep. Will be much easier with https://github.com/taptapship/wiredep/issues/235 I think
