### ISSUE TITLE
Option to include scripts with async or defer attribute

### ISSUE THREAD

**Issue by alippai** [taptapship/wiredep#141]
There is no option to include the scripts with async or defer attributes. 
https://github.com/taptapship/wiredep/blob/1d416df3620a3dc9e13a36240a80df855fae895d/lib/default-file-types.js#L15 

We should be able to pass these options with the bower comment parameters.

**Comment by jorgecasar** [comment]
The full config code to make it works, to avoid read code ;)

```
grunt.initConfig({
  […]
  wiredep: {
    app: {
      […]
      fileTypes: {
        html: {
          replace: {
            js: '<script defer src="{{filePath}}"></script>'
          }
        }
      }
    }
  }
  […]
});
```
