### ISSUE TITLE
Adding an option to edit 'eliteDependencies'

### ISSUE THREAD

**Issue by plequang** [taptapship/wiredep#143]
Hi,

Using wiredep (grunt-wiredep) with a polymer based project, I have the same kind of issue as https://github.com/webcomponents/webcomponentsjs/issues/48

After looking at the code, it seems this is the 'eliteDependencies' list in detect-dependencies.js that makes jquery appear before polymer 'webcomponentsjs'.

Do you think it would be possible to add an option to wiredep so that one can specifiy this eliteDependencies list ?

Thanks

**Comment by eddiemonge** [comment]
This has been removed
