### ISSUE TITLE
Start * expressions for multiple file selection in overrides.

### ISSUE THREAD

**Issue by topless** [taptapship/wiredep#144]
I am trying to grab all the less files from a project. My overrides object
```
  "overrides": {
    "flag-icon-css": {
      "main": [
        "less/*.less"
      ]
    }
```
What I get as a result in my css file 
```
@import "../../bower_components/flag-icon-css/less/*.less";
```
When I would expect a list of imports with each less file.
Is it me that is missing something or the `overrides` expect an explicit list of each file? I am using it with `grunt-wiredep` if that affects in any matter. Thanks.

**Comment by robertbaker** [comment]
It's 2015 :)

**Comment by cvrebert** [comment]
Note that using globs in `main` is invalid in a normal `bower.json`; see https://github.com/bower/bower.json-spec/commit/0b34d2bb0bdd4fa31fa9728f787f49e170e41f99#diff-04c6e90faac2675aa89e2176d2eec7d8R92

**Comment by stephenplusplus** [comment]
Thanks @cvrebert. I think we should probably stay away from supporting globs. It would be dangerous, as it could potentially yield different results with each package update.

Closing, but feel free to continue discussing if you think I'm missing something.
