### ISSUE TITLE
Directory content not copied although it is defined in 'main'

### ISSUE THREAD

**Issue by ahmadalfy** [taptapship/wiredep#150]
Greetings,

Font-awesome's [`bower.json`](https://github.com/FortAwesome/Font-Awesome/blob/master/bower.json#L10-L13) file has a `main` array that contain the assets that should be injected

      "main": [
        "./css/font-awesome.css",
        "./fonts/*"
      ],

The CSS reference is injected to the markup as expected. However, the fonts directory is completely ignored. From my understanding, `wiredep` should copy that directory to the destination defined. I tried to search where should I define that destination but I couldn't. My wiredep task is as follow

    wiredep: {
      app: {
        ignorePath: /^\/|\.\.\//,
        src: [
          '<%= config.app %>/includes/_head.jade',
          '<%= config.app %>/includes/_scripts.jade'
        ],
        exclude: [
          'bower_components/bootstrap/dist/js/bootstrap.js',
          'bower_components/modernizr/modernizr.js'
        ]
      }
    },

How can I tell `wiredep` where to copy the fonts? Thanks.

**Comment by CWSpear** [comment]
`wiredep` does not copy anything. It just injects references. I think the functionality you're looking for is https://www.npmjs.com/package/gulp-bower-files or https://www.npmjs.com/package/main-bower-files
