### ISSUE TITLE
Phaser not getting wired

### ISSUE THREAD

**Issue by djmittens** [taptapship/wiredep#155]
I installed phaser using `bower install --save phaser` however it doesnt look like its getting wired, while lodash is for example.  Im not sure if its something i am doing wrong, it is a bug or phaser is just not packaged properly.

**Comment by stephenplusplus** [comment]
Looks like it should be working: https://github.com/photonstorm/phaser/blob/v2.2.2/bower.json#L9

All a package needs is a `bower.json` with a `main`. How are you running `wiredep`?

**Comment by djmittens** [comment]
Im using `gulp-wiredep` plugin similar to this,

```javascript
// inject bower components
gulp.task('wiredep', function () {
  var wiredep = require('wiredep').stream;

  gulp.src('app/*.html')
    .pipe(wiredep())
    .pipe(gulp.dest('app'));
});
```

So i install lodash and phaser which makes my bower.json look like this (minus name / description for discretion :smiley_cat: ).

```json
{
  "main": "index.html",
  "keywords": [
    "game",
    "html5",
    "webgl",
    "rpg"
  ],
  "license": "Private",
  "homepage": "ngrid.me",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "phaser": "~2.2.2",
    "lodash": "~3.0.0"
  }
}
```

So when i dow `gulp wiredep` only lodash shows up.

Ok so as i was typing this long ass post it started working all of a sudden so ill keep this open, but daaam i spent a lot of time trying to get this to work.

**Comment by stephenplusplus** [comment]
That's frustrating :( I tried and it works for me, too. Computers are mean sometimes. Thanks for taking the time to report, glad everything is working now!
