### ISSUE TITLE
not reading relative path correctly?

### ISSUE THREAD

**Issue by JaKXz** [taptapship/wiredep#159]
Font Awesome's bower.json defines their main files like this:
```json
...
  "main": [
    "./css/font-awesome.css",
    "./fonts/*"
  ],
...
```

However, the css file is not put in to my html files when I call wiredep as normal. So, what I have to do to make it work is have overrides that use the "less explicit"? relative path, like so:

```json
  "overrides": {
    "font-awesome": {
      "main": ["css/font-awesome.css", "fonts/*"]
    }
  }
```

which makes the wiredep task work correctly. I'm not sure why these two are handled differently, because from the folder `bower_components/font-awesome/` they mean the same thing. Thoughts?

**Comment by stephenplusplus** [comment]
Hmm, I'm not sure either. I was able to get it working: https://github.com/stephenplusplus/wiredep-159

**Comment by JaKXz** [comment]
Strange. I thought I was seeing the issue with the gulp task, but it seems fine now. Sorry for the noise!

**Comment by JaKXz** [comment]
So, @stephenplusplus it looks like I had font-awesome in my `devDependencies`, which is why they weren't wired to my html files. That sounds like correct behaviour right?

**Comment by stephenplusplus** [comment]
Yes! devDependencies are ignored from being included alongside your dependencies, however, it is possible to overrule this behavior by setting `devDependencies: true`.

**Comment by JaKXz** [comment]
Excellent, thank you. Again, apologies for not reading closer.
