### ISSUE TITLE
wiredep multiple files?

### ISSUE THREAD

**Issue by sandrodz** [taptapship/wiredep#164]
Is it possible to edit multiple files?

{
  "scripts": {
    "postinstall": "wiredep -s path/to/src.html",
    "postinstall": "wiredep -s path/to/src2.html"
  }
}

**Comment by sandrodz** [comment]
So, I figured it out.

{
"scripts": {
"postinstall": "./postinstall.sh"
}
}

And inside postinstall.sh whatever you want, like:
wiredep -s path/to/src.html
wiredep -s path/to/src2.html
wiredep -s path/to/src3.html

**Comment by stephenplusplus** [comment]
Sorry I missed this ticket, @sandrodz. That solution is probably the best, but another option that should work would be something with globs:

```json
{
  "scripts": {
    "postinstall": "wiredep -s views/**/*.html"
  }
}
```

I haven't tested though, so forgive me if you try and it doesn't work.

Thanks for coming back to post your solution!

**Comment by Ricecoder** [comment]
Passing files with different filetypes is also a little wonky:

    wiredep --src 'src/index.html,src/scss/main.scss'

Does not wire _anything_. Instead:

    wiredep --src src/index.html --src src/scss/main.scss

Uh, sure. That makes sense. Thanks, @al-the-x.
