### ISSUE TITLE
Make the src option default to index.html?

### ISSUE THREAD

**Issue by stevemao** [taptapship/wiredep#165]

**Comment by stevemao** [comment]
Also, return an error when file is not found?

**Comment by stephenplusplus** [comment]
Sure, pr welcome :)

**Comment by eddiemonge** [comment]
I want to say no to defaulting as that would mean index.html is adjacent to whatever is running this and that seems weird. But I do want to say yes to return an error when file not found

**Comment by stevemao** [comment]
In fact, the cli should probably be considered redesigned.

**Comment by eddiemonge** [comment]
going to close this. If it should be for CLI it can be opened on that repo.
