### ISSUE TITLE
feature: "include"

### ISSUE THREAD

**Issue by boneskull** [taptapship/wiredep#168]
#### Use case

I have two template files that must be modified with dependencies. 

Template *A* is the `<head>`; here, I expect any `.css` and select `.js` files to be inserted.  Once these are loaded, the application will begin to render, and we use them to display a "loading" spinner.

Template *B* lives at the bottom of the `<body>` tag.  This is the main application code and dependencies.

Currently, I must manage two lists of regular expressions to exclude filetypes and all files from various packages, corresponding to two Grunt targets for `wiredep`.  This is a pain.

#### Proposal

Add two options:

- `include`: `{Array}` Files matching these regular expressions will be explicitly included.  
- `order`: `{Array}` Think "allow, deny".  If present, defines whether `include` overrides `exclude`, or vice versa

Example:

```js
// Exclude all .js files, then include all .js containing the string "foo"
var opts = {
  include: [/foo.*\.js/],
  exclude: [/\.js/],
  order: ['exclude', 'include']
}; 
```

**Comment by stephenplusplus** [comment]
How about just using wiredep for one template, and manually inject the excluded references from it in your other template? include, exclude, and order is too confusing imo.

**Comment by stylehuan** [comment]
@boneskull approve！！！

**Comment by stephenplusplus** [comment]
Maybe having two wiredep() instances, one for the head and one for the body, will make this easier to handle in your code.

**Comment by boneskull** [comment]
@stephenplusplus would this not necessitate two `bower.json` files?
