### ISSUE TITLE
outdated lodash - improving performance

### ISSUE THREAD

**Issue by igorlino** [taptapship/wiredep#169]
There is a newer version of lodash (3.3.1) which  improved performance 20-40% overall  by better utilizing the JIT in JavaScript engines, using internal helper functions that avoid optimization disqualifications & increase the likelihood of function inlining.

lodash 3.0.0 is 40%  (1.40x) faster than lodash 2.4.1.

In v3 also introduced were lazily evaluated chaining for massive performance wins in certain scenarios.

Any chance to update to the latest release?

**Comment by stephenplusplus** [comment]
PR welcome :)

**Comment by igorlino** [comment]
Alright, PR at https://github.com/taptapship/wiredep/pull/192

**Comment by igorlino** [comment]
ok, try no.2,  PR at https://github.com/taptapship/wiredep/pull/193

**Comment by eddiemonge** [comment]
As I said in that PR, might look into removing lodash entirely. Short term updating is fine if the code can be made to work without changing the current output

**Comment by eddiemonge** [comment]
58b9441b48a6e96f0d9c8993fd59dbef64a9be75
