### ISSUE TITLE
is it possible to determine the file path upon file injection

### ISSUE THREAD

**Issue by xtianus79** [taptapship/wiredep#172]
for now it seems it determines the path but what if we need to alter that path?

**Comment by sixertoy** [comment]
Hey

Have been lookin for the "replace" conf ?

**Comment by xtianus79** [comment]
I fixed it with file path

            cshtml: {
                src: [
                    '<%%= app %>/**/*.cshtml'
                ],
                fileTypes: {
                    html: {
                        block: /(([\s\t]*))(\n|\r|.)*?()/gi,
                        detect: {
                            js: /<script.*src=['"](.+)['"]>/gi,
                            css: /<link.*href=['"](.+)['"]/gi
		                },
                        replace: {
                                js: '<script src="~/lib{{filePath}}"></script>',
                                css: '<link rel="stylesheet" href="~/lib{{filePath}}" />'
                        }
                    }
                },
