### ISSUE TITLE
bower overrides, not injecting css

### ISSUE THREAD

**Issue by robertbaker** [taptapship/wiredep#175]
Bower overrides injects js, but it does not inject css,scss or any other preprocessor.

**Comment by stephenplusplus** [comment]
Can you give me info about your project including configuration files and how I can reproduce?

**Comment by robertbaker** [comment]
Using Yeoman Generator: https://github.com/Swiip/generator-gulp-angular
My overrides in bower.json:
"overrides": {
    "material-design-icons": {
      "main": "./scss/material-design-iconic-font.scss"
    }
  }

I used to have other overrides that were css not scss.

Currently, I'm using the vendor.scss provided in the generator I'm using to inject scss via ```@import```
(you must choose bootstrap-sass option in v0.10 of the generator to get the vendor.scss option)

Using the gulp files provided in the generator.

I'll try to get you a full project that you can reproduce, but it may take me a few days.

**Comment by stephenplusplus** [comment]
I noticed a couple things with that generator. My scaffolded `src/app/vendor.scss` looked like:

```scss
$icon-font-path: "../../bower_components/bootstrap-sass-official/assets/fonts/bootstrap/";

@import '../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap';
```

wiredep needs placeholders to know where to inject references:

```scss
// bower:scss
// endbower
```

Also, I don't believe the inject task is configured to look for SCSS files: https://github.com/Swiip/generator-gulp-angular/blob/v0.10.0/app/templates/gulp/_inject.js#L59.

Additionally, I used your material-design-icons as a reference, and it doesn't seem to have a file called `./scss/material-design-iconic-font.scss` in it, but maybe I was just on a different version.

If you can confirm this still won't work after pointing wiredep to your SCSS file which has placeholders like shown above, a test case will definitely be appreciated :)

**Comment by robertbaker** [comment]
The bower pkg is actually: material-design-iconic-font.

I am no longer using that package (or the override example I gave).
I do have an personal project that is using some overrides, I'll do some testing when I have time.
