### ISSUE TITLE
do overrides do more than just main?

### ISSUE THREAD

**Issue by dtracers** [taptapship/wiredep#178]
example:
```
overrides: {
    'jquery': {
        'dependencies': {
            'projectIwantJqueryToDependOn' : 'version'
        }
    }
}
```

**Comment by stephenplusplus** [comment]
What effect would you hope it to have? If you were to do that, wiredep would try to get information about `bower_components/projectIwantJqueryToDependOn` to find if it has a `main` file to inject as well as to determine the sorting order.

**Comment by hzpz** [comment]
You can use this to override unwanted dependencies. For example I used the following snippet

    "overrides": {
      "angularjs-color-picker": {
        "main": "angularjs-color-picker.js",
        "dependencies": {
          "tinycolor": "~1.1.0",
          "angular": "~1.3.0",
          "bootstrap": "~3.3.0"
        }
      }
    }

to override the [original dependency](https://github.com/ruhley/angular-color-picker/blob/master/bower.json) to `angularjs`.

**Comment by CWSpear** [comment]
@hzpz is spot on.
