### ISSUE TITLE
gulp wiredep.stream exclude options

### ISSUE THREAD

**Issue by vadim-p** [taptapship/wiredep#184]
Hello.

Exclude option doesn't work in stream.
gulpfile.js: https://github.com/roots/sage/blob/master/gulpfile.js#L266
Node version: 0.12.2

I tried to use regexp, file name, path, as described in your [istructions](https://github.com/taptapship/wiredep#configuration):
```javascript
wiredep({exclude: [
'bootstrap',
/bootstrap/,
'app/bower_components/bootstrap',
'bootstrap.less',
'bootstrap.css' 
]})
```
but it doesn't work for me.

And when I  try: 
`$ wiredep -s app/index.html -e bootstrap --verbose`
it does.

I'm new with gulp and wiredep, so may be I misunderstood something?

Thanks

**Comment by stephenplusplus** [comment]
Sorry this took so long to look at. The `exclude` option is passed to wiredep the same as from the cli, so it should work the same.  I just made a quick test and things seemed to work as intended. 

Here was my test having only `jquery` as a saved Bower dependency:

```js
'use strict';

var fs = require('fs');
var wiredep = require('wiredep');
var through2 = require('through2');
var File = require('vinyl');

var file = new File({
  cwd: '/',
  path: 'index.html',
  contents: fs.readFileSync('index.html'),
});

var stream = through2.obj();

stream
  .pipe(wiredep.stream({ exclude: ['jquery'] }))
  .pipe(through2.obj(function (data) {
    // data.contents:
    //
    //   <!-- bower:js -->
    //   <!-- endbower -->
  }));

stream.end(file);
```

`exclude` with `wiredep.stream` is being used in production with the Yeoman generator generator-gulp-webapp. If you haven't already found a better solution to the problem, maybe [check out how they're doing it](https://github.com/yeoman/generator-gulp-webapp/blob/22d42ba8acccac1bc8956a1d0a33f8e19c151669/app/templates/gulpfile.babel.js#L159) to see if something simple was overlooked.
