### ISSUE TITLE
Include another file

### ISSUE THREAD

**Issue by corand** [taptapship/wiredep#190]
Hello,

How can I include another file? For example moment includes "moment.js" automatically, but I want to include instead the file which has languages included, which is in "min/moment-with-locales.js" and "min/moment-with-locales.min.js".

Many thanks

**Comment by stephenplusplus** [comment]
This should work: https://github.com/taptapship/wiredep#bower-overrides :)

**Comment by corand** [comment]
Thanks for the answer, but it doesn't.


    "dependencies": {
        "moment-with-locales": "1.0.0"
      },
      "overrides": {
        "moment-with-locales": {
          "main": "min/moment-with-locales.js"
        }
      }

Error: Error: moment-with-locales is not installed. Try running `bower install`.

**Comment by CWSpear** [comment]
By chance... did you try running `bower install`?

**Comment by stephenplusplus** [comment]
Hmm, I thought the package was `moment`, and you needed a different file. Your dependency is still on `moment` (not `moment-with-locales`, which I can't find on bower.io/search), but you want to override the `main` file for it:

```json
{
  "overrides": {
    "moment": {
      "main": "min/moment-with-locales.js"
    }
  }
}
```

**Comment by corand** [comment]
It looks like it should work but it doesn't... still loading "moment.js"

**Comment by corand** [comment]
The only way I could achieve it was changing directly the main:

    "name": "moment",
    "version": "2.10.3",
    "main": "min/moment-with-locales.js",

Thanks for your help

**Comment by ThibaudD** [comment]
It is a bit late, but if somebody else has the same issue. 
I needed to overrides 'momentjs' package and not 'moment', like that to make it works:
```
{
  "overrides": {
    "momentjs": {
      "main": "min/moment-with-locales.js"
    }
  }
}
```
