### ISSUE TITLE
How to inject additional dependencies not listed in source repo's main?

### ISSUE THREAD

**Issue by mhulse** [taptapship/wiredep#191]
My `bower.json`:

```json
{
  "name": "client",
  "version": "0.0.0",
  "dependencies": {
    "angular": "~1.4.0",
    "angular-route": "~1.4.0",
    "admin-lte": "~2.1.1",
    "bootstrap": "~3.3.4",
    "angular-resource": "~1.4.0",
    "angular-mocks": "~1.4.0",
    "angular-locale": "~0.1.9",
    "angular-bootstrap": "~0.13.0",
    "underscore": "~1.8.3",
    "angular-ui-router": "~0.2.15",
    "moment": "~2.10.3",
    "ngCordova": "~0.1.17-alpha",
    "underscore-contrib": "~0.3.0",
    "angular-chart.js": "~0.7.1"
  },
  "overrides": {
    "admin-lte": {
      "main": [
        "dist/css/AdminLTE.css",
        "dist/css/skins/skin-blue.min.css",
        "dist/js/app.js"
      ],
      "dependencies": {
        "bootstrap": "*"
      }
    }
  }
}
```

In the `admin-lte` section, I can't seem to get the overrides to fully work.

When running:

```bash
$ wiredep --src client/index.html --bowerJson client/bower.json
```

I get:

```html
<!-- bower:css -->
<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
<link rel="stylesheet" href="bower_components/admin-lte/dist/css/AdminLTE.css" />
<link rel="stylesheet" href="bower_components/angular-chart.js/dist/angular-chart.css" />
<!-- endbower -->
```

With no output of `skin-blue.min.css`.

Basically, I'm trying to pull in a CSS skin that's not listed in the source repo's main; for example, here's [AdminLTE's `bower.json`](https://github.com/almasaeed2010/AdminLTE/blob/406de4e708e84ed0abbc08b09870828254a6b2ef/bower.json):

```json
{
  "name": "AdminLTE",
  "version": "2.1.2",
  "homepage": "http://almsaeedstudio.com",
  "authors": [
    "Abdullah Almsaeed <almasaeed2010@gmail.com>"
  ],
  "description": "Admin dashboard and control panel template",
  "main": [
    "index2.html",
    "dist/css/AdminLTE.css",
    "dist/js/app.js",
    "build/less/AdminLTE.less"
  ],
  "keywords": [
    "css",
    "js",
    "html",
    "template",
    "admin",
    "bootstrap",
    "theme",
    "backend",
    "responsive"
  ],
  "license": "MIT",
  "ignore": [
    "/.*",
    "node_modules",
    "bower_components",
    "composer.json",
    "documentation"
  ]
}
```

**Question:** Is what I'm trying to do not possible with wiredep (i.e., get wiredep to inject specific dependencies not listed in the source repo's `bower.json` file)?

Thanks!

**Comment by stephenplusplus** [comment]
Thanks for the detailed report! I tried it out, and my output got `skin-blue.min.css`, so everything appears to be working on my end.

I did a fresh install of global wiredep (`npm install -g wiredep`) and used your exact bower.json. `bower install`, ran wiredep, and it works. Can you try making sure wiredep is up to date, and if it still fails, try creating a new directory with just the bower.json & an html file with a wiredep CSS block?

**Comment by mhulse** [comment]
Hi @stephenplusplus, thank so much for your help, I greatly appreciate it!

> so everything appears to be working on my end.

Oh my gosh, I just tested outside of my project, and everything is working just fine too!

I feel terrible for wasting your time. Sorry that I did not run an independent test before opening an issue.

On the plus side, hopefully it will help others in the future to see an example on how to override and specify specific dependencies not listed in a repo's/package's main file. :+1: 

Thanks so much for your time, and awesome code, I really appreciate it!

**Comment by mhulse** [comment]
Lol, I just discovered why it wasn't working!

I had included the skin outside of the `wiredep` html comment:

```html
<link rel="stylesheet" href="bower_components/admin-lte/dist/css/skins/skin-blue.min.css" />
```

We were doing that because we hadn't setup overrides yet. During my tests, I left that line in the template (outside of the `bower:css` comment).

 As soon as I removed the skin CSS call, and ran `wiredep`, it worked!

Awesome. Thanks again @stephenplusplus!

**Comment by stephenplusplus** [comment]
No problem at all, I'm glad it works now! Our next wiredep release will have that behavior removed, because of this exact issue (explained [here](https://github.com/stephenplusplus/grunt-wiredep/issues/133#issuecomment-107433237) if you're interested).

Sorry you ran into this!
