### ISSUE TITLE
Force remove extension on SASS

### ISSUE THREAD

**Issue by brunowego** [taptapship/wiredep#201]
Only for "pass" in linters verifications (SASS Lint for example), at this moment I need use "hack" like this:

```js
fileTypes: {
  scss: {
    block: /(([ \t]*)\/\/\s*bower:*(\S*))(\n|\r|.)*?(\/\/\s*endbower)/gi,
    detect: {
      scss: /@import\s['"](.+\.scss)['"]/gi
    },
    replace: {
      scss: function (filePath) {
        var path = filePath.replace('.scss', '').replace('/_', '/');

        return '@import \'' + path + '\';';
      }
    }
  }
}
```

Will be nicer if wiredep does this automatically. Thanks!

**Comment by eddiemonge** [comment]
Why is it a bad thing to specify exactly what you want imported? I think this should fine and maybe that linter is a little too strict.

**Comment by cyrilchapon** [comment]
Well @eddiemonge, I guess [this well known linter](https://docs.codeclimate.com/docs/scss-lint) has the right philosophy and the question is not answered here.
