### ISSUE TITLE
dependencies aren't injected for emojione or bootstrap-saas

### ISSUE THREAD

**Issue by mcfiredrill** [taptapship/wiredep#203]
I don't understand why these dependencies aren't injected into my HTML, they both define a main section in their bower.json files:

https://github.com/Ranks/emojione/blob/master/bower.json#L4
https://github.com/twbs/bootstrap-sass/blob/master/bower.json#L12

I'm using wiredep via the yeoman modern frontend project, I haven't changed any of the configuration from this gulpfile:
https://github.com/endel/generator-modern-frontend/blob/master/app/templates/gulpfile.js

My bower.json:
```
{
  "name": "package",
  "version": "0.0.0",
  "dependencies": {
    "modernizr": "~2.8.3",
    "normalize-css": "~3.0.2",
    "bourbon": "~4.2.2",
    "jplayer": "~2.9.2",
    "socket.io-client": "~1.3.5",
    "bootstrap-sass": "~3.3.5",
    "js-emoji": "~1.0.0",
    "emojione": "~1.4.1",
    "fullcalendar": "~2.3.2",
    "moment": "~2.10.3",
    "jsTimezoneDetect": "~1.0.6",
    "moment-timezone": "~0.4.0",
    "showdown": "~1.1.0"
  }
}
```

My package.json:
```
{
  "private": true,
  "engines": {
    "node": ">=0.12.0"
  },
  "scripts": {
    "start": "gulp serve"
  },
  "devDependencies": {
    "autoprefixer-core": "^5.1.7",
    "babelify": "~5.0.4",
    "browser-sync": "^2.2.1",
    "browserify": "~10.2.4",
    "del": "^1.1.1",
    "gulp": "^3.9.0",
    "gulp-awspublish": "^1.0.6",
    "gulp-babel": "~4.0.0",
    "gulp-cache": "^0.2.8",
    "gulp-csso": "^1.0.0",
    "gulp-if": "^1.2.5",
    "gulp-imagemin": "^2.2.1",
    "gulp-jshint": "^1.9.2",
    "gulp-load-plugins": "^0.8.1",
    "gulp-minify-html": "^1.0.0",
    "gulp-postcss": "^4.0.3",
    "gulp-sass": "^1.3.3",
    "gulp-size": "^1.2.1",
    "gulp-sourcemaps": "^1.5.0",
    "gulp-uglify": "^1.1.0",
    "gulp-useref": "^1.1.1",
    "jshint-stylish": "^1.0.1",
    "main-bower-files": "^2.5.0",
    "opn": "^1.0.1",
    "through2": "~0.6.3",
    "wiredep": "3.0.0beta"
  },
  "dependencies": {
    "envify": "^3.4.0"
  }
}
```

I'd appreciate some help, thanks!

**Comment by mcfiredrill** [comment]
Ah, I actually see the typo in emojione's JSON now. I can file a PR for that.
Still no idea about bootstrap-saas, though.

**Comment by al-the-x** [comment]
For Bootstrap, the main files are Sass (scss) files, not CSS, so wiring them up in your HTML files doesn't make sense. Put a set of comments in a Sass file instead, e.g.

    // bower:scss
    // endbower 

Then supply that file to the command instead.

**Comment by PBartrina** [comment]
Boostrap-sass dependencies still aren't injected. Even though I override them just to load a js file from it.

**Comment by eddiemonge** [comment]
What is your config?

**Comment by eddiemonge** [comment]
Is this still an issue? If so, I'll reopen

**Comment by PBartrina** [comment]
Not an issue anymore. Good job handling all those PR
