### ISSUE TITLE
Add Wordpress support

### ISSUE THREAD

**Issue by jongamble** [taptapship/wiredep#21]
Not so much an issue as an idea for an improvement.

In wordpress, a good idea is the use the hook into wp_head to include your css and script files. It would be really cool if this, and bower-install, would output a properly formatted wp_enqueue_script or wp_enqueue_style (and register function call) (http://codex.wordpress.org/Function_Reference/wp_enqueue_script) to be installed into the theme functions for wordpress.

When I have more time, I will make a fork and try to work on it.

Thanks for the great tool!

**Comment by davidrhoderick** [comment]
So I'm using the gulp version of this plugin and I have the following code in my functions.php

    function bower_enqueue_assets() {
      /*
       * BOWER - Generated by `gulp wiredep` - do not modify, use `bower install`
       *         and `bower uninstall` and run `gulp wiredep` to update this.
       * *************************************************************************/

      // bower:css
      // endbower

      // bower:js
      // endbower
    }

    add_action('wp_enqueue_scripts', 'bower_enqueue_assets');

And the following in my gulpfile.js

    gulp.src('functions.php')
      .pipe(wiredep({
        fileTypes: {
          php: {
            // ignorePath: '../',
            block: /(([ \t]*)\/\/\s*bower:*(\S*))(\n|\r|.)*?(\/\/\s*endbower)/gi,
            detect: {
              js: /script\(.*src=['"]([^'"]+)/gi,
              css: /link\(.*href=['"]([^'"]+)/gi
            },
            replace: {
              js: function(filePath){
                var fileName = filePath.substring(filePath.lastIndexOf('/')+1);
                var wpHandle = fileName.replace(".","-");
                return "wp_enqueue_script('"+wpHandle+"',get_stylesheet_directory_uri() . '/"+filePath+"');";
              },
              css: function(filePath){
                var fileName = filePath.substring(filePath.lastIndexOf('/')+1);
                var wpHandle = fileName.replace(".","-");
                return "wp_enqueue_style('"+wpHandle+"',get_stylesheet_directory_uri() . '/"+filePath+"');";
              }
            }
          }
        },
        onError: function(err) {
          console.log(err.code);
        }
      }));

Before, I was using the gulp wiredep plugin in other files and it worked great; however, now the wiredep function does nothing to my functions.php.  The gulpfile, functions, and bower_components files/folders are in the same directory.  Why wouldn't this be working?

**Comment by davidrhoderick** [comment]
Never mind; forgot my gulp.dest!  However, if you want the gulp equivalent, here it is in its complete glory:

    gulp.src('functions.php')
      .pipe(wiredep({
        fileTypes: {
          php: {
            block: /(([ \t]*)\/\/\s*bower:*(\S*))(\n|\r|.)*?(\/\/\s*endbower)/gi,
            detect: {
              js: /script\(.*src=['"]([^'"]+)/gi,
              css: /link\(.*href=['"]([^'"]+)/gi
            },
            replace: {
              js: function(filePath){
                var fileName = filePath.substring(filePath.lastIndexOf('/') + 1);
                var wpHandle = fileName.replace(".","-");
                return "wp_enqueue_script('" + wpHandle + "', get_stylesheet_directory_uri() . '/" + filePath + "');";
              },
              css: function(filePath){
                var fileName = filePath.substring(filePath.lastIndexOf('/') + 1);
                var wpHandle = fileName.replace(".","-");
                return "wp_enqueue_style('" + wpHandle + "', get_stylesheet_directory_uri() . '/" + filePath + "');";
              }
            }
          }
        }
      }))
      .pipe(gulp.dest('./'));

EDIT: removed debugging statements.
