### ISSUE TITLE
wiredep not working with bootstrap 3.3.5

### ISSUE THREAD

**Issue by joaocc** [taptapship/wiredep#210]
https://github.com/twbs/bootstrap/issues/16663

**Comment by joshtoo** [comment]
@joaocc - This is technically not wiredep's fault, this is a tool getting shafted by another. Bower deciding to change the spec for "main" and made a gigantic mess of things. You will have the same problem with font-awesome ~4.4.0

Workaround ( In your bower.json )

```javascript
  "overrides": {
      "bootstrap": {
         "main":[
            "dist/css/bootstrap.css"
         ]
      },
      "font-awesome": {
         "main":[
            "css/font-awesome.css"
         ]
      }
   },
```

All that being said, the statement "let wiredep work it's magic" really no longer applies as you now have to verify every single package you add and want to inject.

**Comment by joaocc** [comment]
Hi. 
I agree with you that wiredep is not the cause of the situation, but if you follow the conversations it seems to be more about the blame than the alleviation of pain this has caused :). 
I very much prefer an approach to get things rolling again, which is what you did!
Thanks!

**Comment by joaocc** [comment]
Still not working. 
I tried this on a freshly installed skeleton (https://github.com/softserveinc/generator-ng-ss). 
Doing "gulp inject" includes other components but not bootstrap.
I tried both your workaround and with  bootstrap <= 3.3.2 (which has the "old-style" bower.json main.
I will also open the issue in the generation tracker, because it may be something else causing it.
Any hints?
Thx

**Comment by joshtoo** [comment]
@joaocc - Give me a few minutes, I'll clone that repo and take a look at it.

**Comment by joaocc** [comment]
I just did that now, to be sure. It seems that bootstrap.css is being copied to app/vendor.css. This makes sense, because wiredep is being configures in ./gulp/conf.js to ```  exclude: [/bootstrap.js$/, /bootstrap\.css/], ```.
Removing the exclude makes bootstrap.js show up.
Adding your workaround makes bootstrap.css show up.
I'm sorry for the false alarm.
Once again thanks for taking the time and congrats for the amazing tool.

**Comment by crrollyson** [comment]
Not ideal, but I rolled back to BS version 3.3.4 and setting up like this:

```
bower install --save bootstrap#3.3.4

bower_concat: {
  all: {
    dest: {
      'js': 'path/to/file/_bower.js',
      'css': 'path/to/file/_bower.css'
    }
  }
}
```
