### ISSUE TITLE
Adding configuration points for data-* attributes

### ISSUE THREAD

**Issue by rcchen** [taptapship/wiredep#211]
Blanket relies on a `data-cover-adapter` attribute in order to attach Blanket to a non-QUnit test runner. Is it possible to attach attributes to the links generated like so?

```
<script src="./bower_components/blanket/dist/qunit/blanket.js"
    data-cover-adapter="./bower_components/blanket/dist/mocha/blanket_mocha.js"></script>
```

**Comment by eddiemonge** [comment]
I want to say no. And that is bad adding code just for tests like that. Have you tried Istanbul or any of the other code coverage tools that don't require changing your source code so they work? Especially since their site has this:

> FYI: Please note that this repo is not actively maintained

> If you're looking for a more active project for JavaScript code coverage, I recommend Istanbul.
