### ISSUE TITLE
Bower 'Whitelist'

### ISSUE THREAD

**Issue by someyoungideas** [taptapship/wiredep#221]
Would there be a way to create a bower `include`? It would be similar to the current `exclude`, however I want to reference only specific bower packages, instead of all of them and then exclude 90%.

**Comment by eddiemonge** [comment]
If you are doing that then why do you have them in your dependency list to begin with?

**Comment by eddiemonge** [comment]
Is this still an issue? If so, I'll reopen

**Comment by darkmavis1980** [comment]
This would be handy, for example in application where you have two pages, like a login page and an application page, and in the login you want only some of the files, and not all
