### ISSUE TITLE
cli -b and --bowerJson produce different results

### ISSUE THREAD

**Issue by danielsiwiec** [taptapship/wiredep#222]
If running via this CLI, **-b filename** does not behave properly, as the scripts reads the JSON contents of the *filename*, puts it in the same **-b** property and later overwrites it again with just the *filename*.
This only happens for **-b**, not for **--bowerJson**.

PR to follow soon.

**Comment by danielsiwiec** [comment]
@stephenplusplus Hi, could you take a quick look at this?

**Comment by stephenplusplus** [comment]
Sorry for taking so long and thanks for helping out! I have a quick comment to make over on the PR.

**Comment by danielsiwiec** [comment]
Updated the PR per your suggestion
