### ISSUE TITLE
fileType replacement options are not merged with defaults

### ISSUE THREAD

**Issue by SaigeArk** [taptapship/wiredep#224]
Node: 4.2.3
Wiredep: 2.2.2
Lodash: 3.10.1

When using wiredep as part of a gulp build process the fileType replace options are not merged with the defaults. It looks like changing like 87 of wiredep.js from:
```$._(optsFileTypes).each(function (fileTypeConfig, fileType)```
to 
```$._.each(optsFileTypes, function (fileTypeConfig, fileType)```

fixes the problem.

**Comment by stephenplusplus** [comment]
Can you show the gulpfile's configuration? I just tried each way, and they're doing the same thing for me.

**Comment by SaigeArk** [comment]
In trying to produce a test case for you I looked deeper. It is not an issue with node, lodash, or wiredep. When running on windows I get an error when trying to remove the node_modules folder. In order to fix this I have run the flatten-packages command. This is what breaks the replace function.

What is odd to me is that in order to fix it I have to uninstall and reinstall wiredep but **not** lodash. 
This also occurs with wiredep 3.0.0

**Comment by eddiemonge** [comment]
So is this fixed or not fixed? Curious also to what npm version you are running?
