### ISSUE TITLE
wiredep not able to insert deps for local repository

### ISSUE THREAD

**Issue by cloudtronics** [taptapship/wiredep#228]
i have a bower.json component 
 "dependencies": {
    "mycore": "C:\\mycore"
  },
my html

    

but grunt build never able to insert any line in the HTML..
where as below defiition works fine , inserts scripts line to html
"dependencies": {
   "angular-animate": "^1.4.0",

===
the above local component has a bower.json with main definition
 "main": "./dist/scripts.main.js",  
still HTML dont update with scripts.main.js

Pls help..

**Comment by randycasburn** [comment]
Is is possible you have a <script> tag for the same resource in the src file (index.html) and have that <script> tag commented out with HTML comments?



If so, remove that comment and try again.

**Comment by eddiemonge** [comment]
I'm wondering if its because you have specified windows file path. Maybe try using unix and see if that fixes it?

**Comment by eddiemonge** [comment]
Is this still an issue? If so, I'll reopen
