### ISSUE TITLE
Problem if html file is outside wwwroot

### ISSUE THREAD

**Issue by galmok** [taptapship/wiredep#229]
When I use wiredep to inject my libs that are located in wwwroot/lib into my html file (store in project root/Scripts), then resulting injected files all come prefixed with "../wwwroot". I use the wiredep option 'directory' with a path that points to the lib folder.

<script src="../wwwroot/lib/jquery/dist/jquery.js"></script>

When processing the html file, the resulting html file is placed in wwwroot.

Is there any option to wiredep that will allow me to have it strip "../wiredep/" from all references inserted into the html file? Or can I rewrite the html file path (just in memory) prior to wiredep receiving it?

**Comment by eddiemonge** [comment]
`ignorePath` is what you are looking for https://github.com/taptapship/wiredep#configuration
