### ISSUE TITLE
fileTypes > replace don't working

### ISSUE THREAD

**Issue by Tibicenas** [taptapship/wiredep#241]
Ok the point is[ this issue about take .min version of the css or files pointed within bower.json](https://github.com/taptapship/wiredep/issues/52)

We cannot ask Wiredep to search inside each package to take that specific file, but WE CAN modify the output injected into our HTML ( this is dangerous in case a package hasn't .min version, but thats not question)

So what i'm trying to do is something like this:

```javascript
 var wiredepOptions = function() {
    var options = {
      ignorePath : '../..',
      bowerJson  : require('./bower.json'),
      directory  : './bower_components/',
      fileTypes  : {
        html: {
          block: /(([ \t]*)<!--\s*bower:*(\S*)\s*-->)(\n|\r|.)*?(<!--\s*endbower\s*-->)/gi,
          detect: {
            js: /<script.*src=['"]([^'"]+)/gi,
            css: /<link.*href=['"]([^'"]+)/gi
          },
          replace: {
            js: function(filePath) {
              var minFilePath = filePath.replace('.js', '.min.js');
              return '<script src="{{minFilePath}}"></script>';
            }
          }
        }
      }
    };
    return options;
  };
```

But this key fileTypes > >  replace:  looks do nothing !

**Comment by stephenplusplus** [comment]
Works for me: https://gist.github.com/stephenplusplus/05649c7946fac9818cab6a805ad45443

> We cannot ask Wiredep to search inside each package to take that specific file,

I added in a check for a min file. If it's found, it's used. If not, it'll just use the original file.

**Comment by Tibicenas** [comment]
Hi @stephenplusplus , your code looks like the next stage of mine ( worrying about if the .min exists or not ) looks great, but doesn't work on my gulpfile :(,  inject like always.

***Folder structure***
```shell
- rootfolder/
  -bower_components/
  - node_modules/
  - src/
    - client/
      - 'index.html'     // With the <!-- bower:js --><!-- endbower -->
  - 'gulpfile.js'
  - 'package.json'
```


***Package.json chunk***
```shell
"devDependencies": {
    "gulp": "^3.9.1",
    "wiredep": "^4.0.0"
  }
```


***Gulpfile***
```javascript
const gulp      = require('gulp'),
         wiredep = require('wiredep').stream;

var index = './src/client/index.html',
      options = {
      ignorePath : '../..',
      bowerJson  : require('./bower.json'),
      directory  : './bower_components/',
      exclude    : config.bower.exclude,
      //src: index,
      fileTypes: {
        html: {
          replace: {
            js: function(filePath) {
              var fileIsMinified = filePath.indexOf('min.js') > -1

              if (!fileIsMinified) {
                var possibleMinFilePath = filePath.replace('.js', '.min.js')

                //if (fs.existsSync(possibleMinFilePath)) {
                 filePath = possibleMinFilePath
                //}
              }

              return '<script src="' + filePath + '"></script>'
            }
          }
        }
      }
    };


gulp.task('wiredep', () => {
  return gulp
    .src(index)
    .pipe(wiredep(options))
    .pipe(gulp.dest('./src/client/'));
});
```


I just commented the second if, because i'm not sure how know if i have var fs = require('fs')  ( filesystem right? ) installed

**Comment by stephenplusplus** [comment]
Still works for me. I made the config as simple as it can be (+ fixed the min-file injection) here: https://github.com/stephenplusplus/wiredep-241

**Comment by Tibicenas** [comment]
Hi, and again thanks you so much, i cloned [your repo](https://github.com/stephenplusplus/wiredep-241) but still take the normal version, not the minified.

Step by step: 
1) Clone repo
```shell
git clone https://github.com/stephenplusplus/wiredep-241.git
```
2) Npm install
```shell
npm install
```
3) Run task 
```shell
gulp wiredep
```

4) Output: 
```html
<!-- bower:js -->
<script src="/bower_components/jquery/dist/jquery.js"></script>
<!-- endbower -->
```

5) Kill myself
```shell
sudo kill -me
```

Any idea what is happening here ?   the 'fs' maybe :S ?

**Comment by stephenplusplus** [comment]
I'm not sure what is happening. `fs` is a native module: https://nodejs.org/api/fs.html -- if it's not finding the min file, that could be either:

1. the directory with jQuery doesn't have a min.js file
2. the path is wrong

Do some logging here: https://github.com/stephenplusplus/wiredep-241/blob/aef8d4ab2b185d1d64006fd27111309e6082873f/gulpfile.js#L20 -- see what the file path is and check if that path does actually exist or not.

**Comment by Tibicenas** [comment]
Ok i know what is not working ! but no how tu fix it :S 



I commented the second  if statement to force take the .min version..

```javascript
const fs = require('fs'),
    gulp = require('gulp'),
    path = require('path'),
 wiredep = require('wiredep').stream;

var index = './src/client/index.html',
  options = {
    // Had to comment since I don't know what `config` is
    // exclude    : config.bower.exclude,

    fileTypes: {
      html: {
        replace: {
          js: function(filePath) {
            var fileIsMinified = filePath.indexOf('.min.js') > -1

            if (!fileIsMinified) {
              var possibleMinFilePath = filePath.replace('.js', '.min.js')

              /*if (fs.existsSync(possibleMinFilePath)) {
               filePath = possibleMinFilePath
              }*/
               filePath = possibleMinFilePath
 
            }

            return '<script src="' + filePath.replace('../..', '') + '"></script>'
          }
        }
      }
    }
  };


gulp.task('wiredep', () => {
  return gulp
    .src(index)
    .pipe(wiredep(options))
    .pipe(gulp.dest('./src/client/'));
});
```

Now works, so the problem is with this condition:
```javascript
const fs = require('fs');

fs.existsSync(possibleMinFilePath)
````

In the node Doc if i search fs.existsSync **[looks deprecated](https://nodejs.org/api/fs.html#fs_fs_existssync_path)**

Now say:
 - fs.existsSync(path)#
Stability: 0 - Deprecated: Use [fs.statSync()](https://nodejs.org/api/fs.html#fs_fs_statsync_path) or [fs.accessSync()](https://nodejs.org/api/fs.html#fs_fs_accesssync_path_mode) instead.

Did you know how would be the updated way ?

**Comment by stephenplusplus** [comment]
Judging from the error, it's trying to find "/bower_components/jquery/dist/jquery.min.js" which is not the correct path. Imagine you were in your terminal, typing "cd /bower_components/..." would look for a folder called "bower_components" in the root of your hard drive. You likely need a relative path like "bower_components/..." (note the missing `/` at the beginning).

**Comment by Tibicenas** [comment]
That fixed everything ! now even works fs.exitsSync 👍 
But i don't know is adding that slash to the path :S 
Anyway i use substring(1) to remove it and now is sweeeet 
Thank you so much :)
