### ISSUE TITLE
What kind of optional configurations are available?

### ISSUE THREAD

**Issue by computersarecool** [taptapship/wiredep#263]
In the docs you show:
```    
.pipe(wiredep({
      optional: 'configuration',
      goes: 'here'
}))
```
However there is no indication of what configuration options there may be.  Do you have any examples?

**Comment by stephenplusplus** [comment]
https://github.com/taptapship/wiredep#configuration :)

**Comment by computersarecool** [comment]
Aiii! Sorry thanks.
