### ISSUE TITLE
Parsing error on socket.io-client

### ISSUE THREAD

**Issue by Climax777** [taptapship/wiredep#86]
Hi

I think some form of parsing error occurs here. I'm using bower with socket.io-client. When overriding in the grunt-wiredep (or my bower.json) like so:

``` js
overrides: {
    'socket.io-client': {
        main: 'socket.io.js'
    }
}
```

I get the injection: `<script src="bower_components/socket.io-socket.io.js"></script>`

It should be `<script src="bower_components/socket.io-client/socket.io.js"></script>`

Changing the main field to become `main: 'client/socket.io.js'` works.

**Comment by boogiebug** [comment]
For those you still have the problem, please check your wiredep's ```'ignorePath'``` option. I found the same issue according to the value of ```'ignorePath'```, which was set to ```'<%= yeoman.client %>/'```, and resolved to the value of ```'client'``` in my Grunt.js and then affect the ```socket.io-client``` (which also contain ```'client/'``` in it's folder name.)

This might imply that all folders or file names those contain ```'client/'``` will get the same problem.

The issue is around here:
```File: lib/inject-dependencies.js line @ line #79+```

```javascript
     dependencies.
       map(function (filePath) {
         return $.path.join(
           $.path.relative($.path.dirname(file), $.path.dirname(filePath)),
           $.path.basename(filePath)
         ).replace(/\\/g, '/').replace(ignorePath, '');
       })...
```

When the statement ```.replace(ignorepath, '')``` taking action, all substring which equal to the value of ```ignorePath``` will then be converted to a blank string ''

**Comment by piraveen** [comment]
I had the same issue loading the socket.io.js into my angular app. My grunt wiredep task was injecting this line: `<script src="bower_components/socket.io-socket.io.js"></script>
`

Until I updated my grunt wiredep task from:
```
wiredep: {
    options: {
        exclude: [ '/json3/', '/es5-shim/' ]
    },
    client: {
        src: '<%= yeoman.client %>/index.html',
        ignorePath: '<%= yeoman.client %>/',
    }
},
```
to:
```
wiredep: {
    options: {
        exclude: [ '/json3/', '/es5-shim/' ]
    },
    target: {
        src: '<%= yeoman.client %>/index.html',
        ignorePath: './<%= yeoman.client %>/',
    }
},
```

I simply added a `./` to the wiredep `ignorePath` prefix which resulted in `ignorePath: './<%= yeoman.client %>/'`, to let grunt ignore the `./client` folder in my project <strong>root</strong> directory.

result:
```
<script src="bower_components/socket.io-client/socket.io.js"></script>
```

Note: this is just a work around, I can't assure that this would work for everyone. But hope you may get some ideas based on my example.
